### ISSUE TITLE
Question: Resizing/Normalising documents at load time

### ISSUE THREAD

**Issue by bubblobill** [weisJ/jsvg#108]
1. I'm using a variety of SVG images with wild and varied dimensions.
2. I wish to optionally add some stock filters to the documents at load time.

Without having uniform co-ordinates/dimensions, the filters cannot reliably produce the desired effect.

Is it doable or too-hard to scale elements to a given dimension when loading the document?

**Comment by weisJ** [comment]
Could you maybe provide an example for the problem you’re facing? Doesn’t [filterUnits](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/filterUnits) handle this for you?

**Comment by bubblobill** [comment]
The filterUnits do nothing.

The following two images have had the same filter applied. One image has dimensions of 189:189 and the other is 1280:1164. This is the filter:
```
<filter id="noise" x="0%" y="0%" width="100%" height="100%" filterUnits="userSpaceOnUse">
    <feTurbulence baseFrequency="0.01 0.4" result="NOISE" numOctaves="2" />
    <feDisplacementMap in="SourceGraphic" in2="NOISE" scale="20" xChannelSelector="R" yChannelSelector="R"></feDisplacementMap>
</filter>
```
Turbulence feeds the displacement, but the actual displacement is wildly different because the user coordinate systems are on vastly different scales for the whole image.
![treFoliage distorted](https://github.com/user-attachments/assets/3cad34b5-0b84-411f-98c3-615b5930ec58)
![runeCircle distorted](https://github.com/user-attachments/assets/f7fa4cf1-ccb4-4044-9d38-c9a83d6612a4)

**Comment by weisJ** [comment]
You should apply the filter to the top level `svg` element itself. This way you ensure that if all images have the same aspect ratio the filter will use the same bounds for computations. Additionally
- Use `filterUnits="objectBoundingBox"`.
- Use `primitiveUnits="objectBoundingBox"`. This way the `scale` now refers to a fraction of the dimension of the svg image. In your case you probably want a value for `scale` of approximately `0.015`.

The resulting filter looks like this:
````svg
<filter id="noise" x="0%" y="0%" width="100%" height="100%"
        filterUnits="userSpaceOnUse"
        primitiveUnits="objectBoundingBox">
    <feTurbulence baseFrequency="0.01 0.4" result="NOISE" numOctaves="2"/>
    <feDisplacementMap in="SourceGraphic" in2="NOISE" scale="0.015" xChannelSelector="R"
                       yChannelSelector="R"/>
</filter>
````

Note however that jsvg currently doesn't properly handle the effect of `primitiveUnits` on the `scale` property. However this should be an easy fix.

**Comment by bubblobill** [comment]
A solution that is both easier and blindingly obvious, you are a cunning person.
Consider me satisfied, props to you.
