### ISSUE TITLE
SVG Path renders incorrectly

### ISSUE THREAD

**Issue by narutoDev** [weisJ/jsvg#28]
Jsvg renders the svg different than Firefox.

The svg:
```
<svg width="15" height="15" viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M4.5 6.5V3.5C4.5 1.84315 5.84315 0.5 7.5 0.5C9.15685 0.5 10.5 1.84315 10.5 3.5V6.5M2.5 6.5H12.5C13.0523 6.5 13.5 6.94772 13.5 7.5V13.5C13.5 14.0523 13.0523 14.5 12.5 14.5H2.5C1.94772 14.5 1.5 14.0523 1.5 13.5V7.5C1.5 6.94772 1.94772 6.5 2.5 6.5Z" stroke="black"/>
</svg>
```

Comparison between correct (png version) and incorrect (svg version) rendered image:
![issue](https://user-images.githubusercontent.com/70059875/197221257-0ad5d72f-0717-400d-b280-3d94d3dd0c0f.png)

If wanted I can provide more samples of incorrectly rendered images.

**Comment by weisJ** [comment]
Thank you for reporting. I wasn't properly applying attributes on the root svg element.

**Comment by narutoDev** [comment]
Thanks for the fix
