### ISSUE TITLE
Rendering to BufferedImage example

### ISSUE THREAD

**Issue by JohnCaboose** [weisJ/jsvg#34]
Hello, you mention in the README that you can "render to a `BufferedImage`". Can you include a code example for this? You seem to require a reference to a `JComponent` for the render methods and I don't understand how I can get a `BufferedImage` object without it.

My purpose would ultimately be to get an `ImageIcon` that simply takes the `BufferedImage` as a constructor parameter. Thanks for your time and attention.

**Comment by weisJ** [comment]
The `JComponent` parameter is indicated as a nullable parameter:
https://github.com/weisJ/jsvg/blob/82094dbd6f376a55879c63d7cde282ae9499eaa9/jsvg/src/main/java/com/github/weisj/jsvg/SVGDocument.java#L53

Henc you can simply pass `null` to it.
