### ISSUE TITLE
Used by the next IJ version 2023.2

### ISSUE THREAD

**Issue by bric3** [weisJ/jsvg#42]
So not an issue but I noticed this lib gonna power the icon rendering of IJ

https://github.com/JetBrains/intellij-community/commit/93a8fe3d8376a1ee4b4bcf4cf85d991afc01013d

Not sure from where the artifacts comes from though :
```
jar://$MAVEN_REPOSITORY$/com/github/weisj/jsvg/0.1.0-jb.2/jsvg-0.1.0-jb.2.jar
```
https://github.com/JetBrains/intellij-community/commit/93a8fe3d8376a1ee4b4bcf4cf85d991afc01013d#diff-22ee2b02c7957eb3e598c2fa7bfcd2b33d737680e15c587d34eebcf816e23340R5

So congratulations :)

**Comment by weisJ** [comment]
The version is from [this fork](https://github.com/develar/jsvg), which as I understand it will eventualy be phased out. Not sure what differences remain but I think it only pertains to some convenience accessor function into internals used by IJ.

**Comment by bric3** [comment]
Indeed there seems to be some details there 
https://youtrack.jetbrains.com/issue/IJPL-81/Switch-to-JSVG-for-SVG-icon-rendering
