### ISSUE TITLE
CSS is not parsed correctly

### ISSUE THREAD

**Issue by develar** [weisJ/jsvg#46]
SVG:

```
<svg xmlns="http://www.w3.org/2000/svg" id="icons" viewBox="0 0 16 16"><defs><style>.cls-1{fill:#6e6e6e}</style></defs><path d="M5 5h6v1H5zM5 7h6v1H5zM5 9h6v1H5z" class="cls-1"/><path d="M2 2h12v12H2V2Zm2 2v8h8V4H4Z" style="fill-rule:evenodd;fill:#6e6e6e"/></svg>
```

expected: 
<img width="133" alt="Screenshot 2023-08-03 at 15 13 10" src="https://github.com/weisJ/jsvg/assets/350686/209e4cc6-152e-4e7a-a446-7e6f5c5b74a5">

actual: 
<img width="143" alt="Screenshot 2023-08-03 at 15 12 41" src="https://github.com/weisJ/jsvg/assets/350686/d2c05e61-0d00-46f1-8310-786bd374ff22">

Error in the log: 
```
WARNING: Expected 'SEMICOLON' but got 'Token{type=EOF, data='null'}'
```

**Comment by weisJ** [comment]
Yeah the CSS "parser" is far from spec compliant (it's not trying to be), so I expect these sort of issues to pop up :D

Fixed in 6471e61c53356dec2acff0686b4f25d341042df9
