### ISSUE TITLE
Filter causing `clipPath` shift (with soft clip enabled)

### ISSUE THREAD

**Issue by stanio** [weisJ/jsvg#64]
Related to #62, I'm seeing a similar `clipPath` shift when a filter is applied:

* [cross-thick.svg](https://github.com/weisJ/jsvg/assets/1247730/5f065e71-e457-44ee-bbac-d2a98937d3e9)
* [cross-thin.svg](https://github.com/weisJ/jsvg/assets/1247730/e78c3fcf-4299-4c1c-979e-3e7a532df462)

| | JSVG | Chrome | JSVG (no filter) |
|-|-|-|-|
| **cross-thick-128** | <img alt="jsvg-cross-thick-128" src="https://github.com/weisJ/jsvg/assets/1247730/e31a8aa5-b537-45ee-a9da-249eb0c3515e" width="256"> | <img alt="chrome-cross-thick-128" src="https://github.com/weisJ/jsvg/assets/1247730/d08ddbc3-db6d-474f-be49-2bc87c326b83" width="256"> | <img alt="nof-cross-thick-128" src="https://github.com/weisJ/jsvg/assets/1247730/e0e3e3ee-0a70-4f82-a4e7-574fa6ce27b8" width="256"> |
| cross-thick-96 | <img alt="jsvg-cross-thick-96" src="https://github.com/weisJ/jsvg/assets/1247730/acfb775f-190b-44cc-8e5b-7e7cfeb2c8ee" width="256"> | <img alt="chrome-cross-thick-96" src="https://github.com/weisJ/jsvg/assets/1247730/1c7ecdce-e737-4fc0-a4d3-d78e7226806f" width="256"> | <img alt="nof-cross-thick-96" src="https://github.com/weisJ/jsvg/assets/1247730/bbbb4070-6342-486a-b539-68c554cb89ad" width="256"> |
| **cross-thick-64** | <img alt="jsvg-cross-thick-64" src="https://github.com/weisJ/jsvg/assets/1247730/62090386-930c-43c4-9a11-0a582d4cde22" width="256"> | <img alt="chrome-cross-thick-64" src="https://github.com/weisJ/jsvg/assets/1247730/1ab5c6a0-1747-4c0d-8201-ebc234f3675c" width="256"> | <img alt="nof-cross-thick-64" src="https://github.com/weisJ/jsvg/assets/1247730/8c375aa1-7e67-4614-a041-2b2e811c436c" width="256"> |
| cross-thin-128 | <img alt="jsvg-cross-thin-128" src="https://github.com/weisJ/jsvg/assets/1247730/d13e8a40-2204-4c7c-81fa-54c688883890" width="256"> | <img alt="chrome-cross-thin-128" src="https://github.com/weisJ/jsvg/assets/1247730/2cebbb79-ac93-414c-b426-76427a0f6004" width="256"> | <img alt="nof-cross-thin-128" src="https://github.com/weisJ/jsvg/assets/1247730/e254f10b-41e0-4f9a-a03d-281043d8768e" width="256"> |
| **cross-thin-96** | <img alt="jsvg-cross-thin-96" src="https://github.com/weisJ/jsvg/assets/1247730/74de6b5d-7a70-4b4d-b0b5-3c0e24a2c903" width="256"> | <img alt="chrome-cross-thin-96" src="https://github.com/weisJ/jsvg/assets/1247730/0a487042-757e-4996-99e5-d4eb51e31267" width="256"> | <img alt="nof-cross-thin-96" src="https://github.com/weisJ/jsvg/assets/1247730/75eab098-5cb6-4196-933e-741579baa61a" width="256"> |
| cross-thin-64 | <img alt="jsvg-cross-thin-64" src="https://github.com/weisJ/jsvg/assets/1247730/7b447b15-9c9f-4573-a002-79da4a4d5464" width="256"> | <img alt="chrome-cross-thin-64" src="https://github.com/weisJ/jsvg/assets/1247730/7ba785af-7588-4441-a054-ca3dd0a34e7a" width="256"> | <img alt="nof-cross-thin-64" src="https://github.com/weisJ/jsvg/assets/1247730/91fe4cb8-aa79-4852-aaf3-699cb9443b4f" width="256"> |

Look at **cross-thick-128**, **cross-thick-64** and **cross-thin-96**.

I'm using the following rendering hints: `ANTIALIASING=ANTIALIAS_ON, STROKE_CONTROL=STROKE_PURE, SOFT_CLIPPING=SOFT_CLIPPING_ON`

---

The SVG sources contain declarations for the different sizes (64, 96, 128) commented out:

```xml
<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0.5 0.5 384 384" fill="none">
<!--svg xmlns="http://www.w3.org/2000/svg" width="96" height="96" viewBox="-1.5 -1.5 384 384" fill="none"-->
<!--svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0.5 0.5 384 384" fill="none"-->
```

**Comment by weisJ** [comment]
Soft clipping is still unstable and even without filters has some issues.

**Comment by stanio** [comment]
Removing the `SOFT_CLIPPING=SOFT_CLIPPING_ON` hint eliminates the shift at the expense of a heavily aliased result (#59).

I've tried replacing the `clipPath` with a `mask`, like:

```diff
-<path ... clip-path="url(#center-hole)"/>
-<clipPath id="center-hole">
-<path .../>
-</clipPath>
+<path ... mask="url(#center-mask)"/>
+<mask id="center-mask" maskUnits="userSpaceOnUse">
+<path ... fill="white"/>
+</mask>
```

I get an anti-aliased result with a similar shift and unexpected cropping I'm currently trying to figure out (cross-thick-128):

<img alt="cross-thick-128" src="https://github.com/weisJ/jsvg/assets/1247730/50d631c1-716c-4acc-a1fb-7382338d7e7e" width="256">

Again, removing the shadow filter eliminates the mask shift, but I still get the cropping:

<img alt="cross-thick-128-nof" src="https://github.com/weisJ/jsvg/assets/1247730/ed7acb8b-dbc8-4b96-b845-ee9ecc34221a" width="256">

FWIW, I've copied the mask path as a stroke-only overlay (top/last element) for some kind of debugging:

```xml
<path ... fill="none" stroke="red" stroke-width="4" stroke-opacity="0.5"/>
```

<img alt="cross-thick-128-ovr" src="https://github.com/weisJ/jsvg/assets/1247730/979cfe24-5eda-4ea5-81e6-980d8f23687c" width="256">

**Comment by stanio** [comment]
I think I may have found the mask clipping issue.  It appears the mask area never grows beyond:

```xml
<mask x="0" y="0" width="100%" height="100%">
```

even when explicitly specifying the implied:

```xml
<mask x="-10%" y="-10%" width="120%" height="120%">
```

therefore any stroke outside the object's bounding box gets clipped.  It appears to accept a smaller mask area though:

```xml
<mask x="10%" y="10%" width="80%" height="80%">
```

**Comment by weisJ** [comment]
Thank you for investigating this. I am already working on improving the situation. Though the issue lies deeper and needs some architectural restructuring to fully resolve. You are experiencing symptoms of this issue.

**Comment by stanio** [comment]
Would you like me to open a separate ticket for the mask clipping issue?

**Comment by weisJ** [comment]
You can open one so its easier to keep track what is working and what not. Though the underlying issue is the same for all of them.

**Comment by weisJ** [comment]
I have pushes some changes which should resolve most of the issues you are experiencing. I haven't had the time to test alls combinations. Could you please check whether there are any outstanding issues?

**Comment by stanio** [comment]
Trying out current [1.5.0-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/com/github/weisj/jsvg/1.5.0-SNAPSHOT/) (`gradlew --refresh-dependencies` → `1.5.0-20240304.002615-19`), I couldn't find noticeable difference:

-   The exact samples I've attached to this issue description still show a shift for me (using `SOFT_CLIPPING_ON`).  If adjust them to use the full https://github.com/weisJ/jsvg/issues/62#issuecomment-1963061430 workaround – it gets fine, but that was the case already before.

I think I've noticed one new issue related to #65, but I'll expand on it there.

**Comment by stanio** [comment]
Verified with a current 1.5.0-SNAPSHOT – looks as expected.

**Comment by weisJ** [comment]
That's good to hear 👍🏼
