### ISSUE TITLE
Wrong `<mask>` bounds (x, y, widht, height) with the default `maskUnits=objectBoundingBox`

### ISSUE THREAD

**Issue by stanio** [weisJ/jsvg#75]
[`maskUnits`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/maskUnits#mask):

>   For `<mask>`, `maskUnits` defines the coordinate system in use for the geometry attributes (`x`, `y`, `width` and `height`) of the element.
>
>   `objectBoundingBox`
>
>   This value indicates that all coordinates for the geometry attributes represent _**fractions**_ or percentages of the bounding box of the element to which the mask is applied.

Seems like fraction values are interpreted as values in the user coordinate system, instead:

<details>
<summary><code>mask-bounds.svg</code>:</summary>

```xml
<svg xmlns="http://www.w3.org/2000/svg"
    width="100" height="100" viewBox="0 0 100 100">

  <defs>
    <mask id="myMask" maskContentUnits="objectBoundingBox"
        x="-0.5" y="-0.5" width="2" height="2">
      <rect x="-0.5" y="-0.5" width="1" height="1" fill="white" />
    </mask>
  </defs>

  <rect x="15" y="15" width="160" height="160" mask="url(#myMask)"
      fill="white" stroke="blue" stroke-width="20" />

</svg>
```
</details>

Actual | Expected
--- | ---
<img alt="actual" src="https://github.com/weisJ/jsvg/assets/1247730/6fc76b78-6b81-4e01-a4a3-e19cd54da769" width="300"> | <img alt="expected" src="https://github.com/weisJ/jsvg/assets/1247730/06429691-b700-44ad-8ed1-fc1d2d5a9c5b" width="300">

**Comment by stanio** [comment]
Alternatively, percentages work fine:

```diff
     <mask id="myMask" maskContentUnits="objectBoundingBox"
-        x="-0.5" y="-0.5" width="2" height="2">
+        x="-50%" y="-50%" width="200%" height="200%">
```

**Comment by weisJ** [comment]
This should be fixed in the latest snapshot version.
