### ISSUE TITLE
Rendering on non-`JComponent`

### ISSUE THREAD

**Issue by bric3** [weisJ/jsvg#76]
Hi I implemented an `javax.swing.html.View` that is able to render SVG using jsvg in a `JEditorPane`.

![image](https://github.com/weisJ/jsvg/assets/803621/14085f57-6416-4aef-a187-e13a54097269)

https://github.com/bric3/intellij-platform-swing-components/blob/main/components/src/main/kotlin/io/github/bric3/ij/ui/util/SvgImageExtension.kt

In this case the `View` is not a `JCompnent` and can't be passed to the `render` method, I noticed the `JComponent` is used to get the font. I wonder if the `render` method could be have a overload with a font provider ?

Note at this time I don't have issues with the render, it's just that I wondered how was used the `JComponent` and noticed it's used to get the font.

**Comment by weisJ** [comment]
The `JComponent` is also used as an `ImageObserver` for external images. The appropriate thing to do here is to implement `PlatformSupport` for `View` and call `SVGDocument::renderWithPlatform` with a `Graphics2DOutput`. For convenience I could provide a method that takes a `PlatformSupport` and `Graphics2D` to avoid having to configure the `Graphics2DOutput` on your own.

**Comment by stanio** [comment]
There's the [`View.container`](https://docs.oracle.com/en/java/javase/21/docs/api/java.desktop/javax/swing/text/View.html#getContainer%28%29) property that usually would be a `JComponent` but is not guaranteed.  I wonder if `JComponentPlatformSupport` really needs a `JComponent` or could do equally well with a `java.awt.Component` (so it could be generalized like `AWTComponentPlatformSupport`)?

**Comment by weisJ** [comment]
Possibly. I’m happy to accept a PR to speed this up. Currently working on resolving #74

**Comment by weisJ** [comment]
Version 1.5.0 has been released
