### ISSUE TITLE
[1.5.0 -> 1.6.0] jsvg hangs thread in some cases

### ISSUE THREAD

**Issue by KlemenDEV** [weisJ/jsvg#88]
After updating to 1.6.0, Swing/AWT thread hangs when FlatSVGIcon is rendered in some cases.

I will provide more info once I figure out when this happens or can create small reproducible example outside scope of https://github.com/MCreator/MCreator where we see this happening after updating to 1.6.0. 1.5.0 works just fine with same code from our side.

**Comment by KlemenDEV** [comment]
Ok this is quite interesting, but this icon in particular causes AWT thread to crash, Java to hang indefinitely. Just place FlatSVGIcon with this SVG on JPanel in JFrame and make it visible and it will crash:

```
<svg width="18" height="18" version="1.1" viewBox="0 0 4.7625 4.7625" xml:space="preserve" xmlns="http://www.w3.org/2000/svg"><defs><marker id="Triangle" overflow="visible" markerHeight="0.35" markerWidth="0.35" orient="auto-start-reverse" preserveAspectRatio="xMidYMid" viewBox="0 0 1 1"><path transform="scale(.5)" d="m5.77 0-8.65 5v-10z" fill="context-stroke" fill-rule="evenodd" stroke="context-stroke" stroke-width="1pt"/></marker></defs><path d="m0.92604 3.0427v0.79375h2.9104v-0.79375" fill="none" stroke="#fff" stroke-miterlimit="3.7" stroke-width=".39688" style="paint-order:normal"/><path d="m2.3812 1.1906v1.8521" fill="none" marker-start="url(#Triangle)" stroke="#fff" stroke-miterlimit="3.7" stroke-width=".52917" style="paint-order:normal"/></svg>
```

It works fine in 1.5.0

**Comment by weisJ** [comment]
If you say that the AWT thread "crashes" do you have a backtrace?

**Comment by KlemenDEV** [comment]
It does not crash in terms of any logs or exceptions, it just simply hangs (no further interaction is possible with the UI). Btw I am on Windows if this is a factor.

**Comment by KlemenDEV** [comment]
Ok no need for FlatSVGIcon and Swing, this is enough to hang main thread of Java program:

```java
import com.github.weisj.jsvg.SVGDocument;
import com.github.weisj.jsvg.parser.SVGLoader;

import java.io.StringBufferInputStream;

class Demo {

    public static void main(String[] args) {
        System.out.println("Start");

        SVGLoader loader = new SVGLoader();
        SVGDocument svgDocument = loader.load(new StringBufferInputStream("""
                <svg width="18" height="18" version="1.1" viewBox="0 0 4.7625 4.7625" xml:space="preserve" xmlns="http://www.w3.org/2000/svg">
                  <defs>
                    <marker id="Triangle" overflow="visible" markerHeight="0.35" markerWidth="0.35" orient="auto-start-reverse" preserveAspectRatio="xMidYMid" viewBox="0 0 1 1">
                      <path transform="scale(.5)" d="m5.77 0-8.65 5v-10z" fill="context-stroke" fill-rule="evenodd" stroke="context-stroke" stroke-width="1pt" />
                    </marker>
                  </defs>
                  <path d="m0.92604 3.0427v0.79375h2.9104v-0.79375" fill="none" stroke="#fff" stroke-miterlimit="3.7" stroke-width=".39688" style="paint-order:normal" />
                  <path d="m2.3812 1.1906v1.8521" fill="none" marker-start="url(#Triangle)" stroke="#fff" stroke-miterlimit="3.7" stroke-width=".52917" style="paint-order:normal" />
                </svg>
                """));

        System.out.println("End");
    }

}
```

**Comment by KlemenDEV** [comment]
End is never printed

**Comment by weisJ** [comment]
Found the issue and just released a new version with the fix. It may take some time until it is fully available through maven. In the meantime you can remove the `paint-order:normal` declaration to fix it.

**Comment by KlemenDEV** [comment]
Wow, that was fast! Thank you for the fix :)

**Comment by KlemenDEV** [comment]
It seems to reference 1.6.1 as maven dependency now works, but no library is loaded. I don't know maven that well so maybe I did not wait long enough.

**Comment by weisJ** [comment]
Ups, I forgot to release it in sonatype. Give it 1-2 hours and it should be up.
